SELECT
C.NAME,
O.ORDER_DATE,
CURR_QTY - PREV_QTY AS QTY_DIFF
FROM
CUSTOMERS C
JOIN (
SELECT
  O.CUSTOMER_ID
  ,O.ORDER_DATE
  ,TOT_QTY AS CURR_QTY
  ,MIN(TOT_QTY) OVER (PARTITION BY O.CUSTOMER_ID ORDER BY ORDER_DATE ROWS BETWEEN  1 PRECEDING AND 1 PRECEDING) AS PREV_QTY
FROM
        (SELECT
                CUSTOMER_ID
              , ORDER_DATE
              , SUM(QUANTITY) AS TOT_QTY
              FROM ORDERS O
              GROUP BY CUSTOMER_ID, ORDER_DATE) O
      ) ORD_STG
ON C.CUSTOMER_ID = ORD_STG.CUSTOMER_ID
WHERE PREV_QTY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ABS(CURR_QTY - PREV_QTY) DESC) = 1